version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: canlookup-db
    env_file:
      - ./dotenv.example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn canlookup_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "80:8000"
    env_file:
      - ./dotenv.example
    depends_on:
      db:
        condition: service_healthy
    container_name: canlookup-web

volumes:
  postgres_data:
